### ISSUE TITLE
MarginSide Top Crash

### ISSUE THREAD

**Issue by DustinBryant** [sboulema/CodeNav#101]
Was just starting to look over the extension to see if it is something I'd like to use. It was great thus far but I was trying to maybe pull it out of the text editor into its own window type. In doing so I was messing with the settings and set the MarginSide (don't remember actual display name but in source code it is Settings.Default.MarginSide) to Top. By doing this it crashed. Now, every time I open a solution or project I get a Microsoft Visual Studio error with the following message:

```
An exception has been encountered. This may be caused by an extension.

You can get more information by examining the file 'LOCATION\ActivityLog.xml'
```

Here's the error from the ActivityLog.xml:

```
  <entry>
    <record>773</record>
    <time>2019/10/11 20:47:08.963</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at CodeNav.CodeNavMargin.CreateGridTop(IWpfTextViewHost textViewHost) in d:\a\1\s\CodeNav\CodeNavMargin.cs:line 208&#x000D;&#x000A;   at CodeNav.CodeNavMargin..ctor(IWpfTextViewHost textViewHost, DTE dte, IOutliningManagerService outliningManagerService, VisualStudioWorkspace workspace, MarginSideEnum side) in d:\a\1\s\CodeNav\CodeNavMargin.cs:line 60&#x000D;&#x000A;   at CodeNav.CodeNavFactory.CreateMargin(IWpfTextViewHost wpfTextViewHost, VisualStudioWorkspace visualStudioWorkspace, IServiceProvider serviceProvider, MarginSideEnum side) in d:\a\1\s\CodeNav\CodeNavMarginFactory.cs:line 108&#x000D;&#x000A;   at CodeNav.CodeNavTopFactory.CreateMargin(IWpfTextViewHost wpfTextViewHost, IWpfTextViewMargin marginContainer) in d:\a\1\s\CodeNav\CodeNavMarginFactory.cs:line 87&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.&lt;AddMargins&gt;b__25_1(IWpfTextViewMarginProvider mp)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

I don't really want it to be on the top side but I couldn't find where the settings were being stored to change it. I attempted to uninstall the extension and re-install but it looks like on the uninstall it doesn't also remove settings so it kept that setting. I'd just like to reset to default if possible.

**Comment by DustinBryant** [comment]
Assuming it takes some time for updates to appear through marketplace?

**Comment by sboulema** [comment]
Had a small hickup in the release to the marketplace, but it is available now: https://marketplace.visualstudio.com/items?itemName=SamirBoulema.CodeNav :D

**Comment by DustinBryant** [comment]
Perfect! Fixed my issue so I can bring it up again and I was able to use separate window as well! Win-Win! This is also the exact extension I was needing/looking for.

You can close this one out.

Thank you!
