### ISSUE TITLE
Filter window optimization

### ISSUE THREAD

**Issue by Brummell67** [sboulema/CodeNav#103]
In the "Filter window", I must do 2 click on ComboBox for show items. It is as if it lost focus.

**Comment by sboulema** [comment]
Grab the new release! 🚀

**Comment by Brummell67** [comment]
Hi friend, 
I just tried, but I get this:
![image](https://user-images.githubusercontent.com/5261273/134529695-e9759347-e465-4b91-8c51-2712ac0c949c.png)
If you need, don't hesitate to ask me.

Thank for your interest and for your great project ;-)

**Comment by sboulema** [comment]
Silly me and my perfect development environment, "Works on my machine"...

Grab the new release! 🚀

**Comment by Brummell67** [comment]
With new v8.5.13, there is crash:
[https://youtu.be/7vnU2v2MdE4](url)
https://youtu.be/7vnU2v2MdE4

**Comment by sboulema** [comment]
The video is private so I cant watch it...

Sorry for the the bad update, will check the log if i can find anything about the crash

**Comment by Brummell67** [comment]
Sorry.
Try now video.

**Comment by sboulema** [comment]
Thanks for the very helpful video, was able to reproduce the problem.

`''DeferRefresh' is not allowed during an AddNew or EditItem transaction.`

**Comment by Brummell67** [comment]
I tried now and doesn't crash, but **filter** and **delete filter** doesn't work.

**Comment by sboulema** [comment]
Try the new release 🚀

**Comment by Brummell67** [comment]
**Delete filter** work now, but doesn't filter.

**Comment by sboulema** [comment]
Filter is working for me?! Do you have a specific example document of code and filter set that is not working? Would love to be able to reproduce it so that I can fix it...

**Comment by sboulema** [comment]
Before filtering:
Check the existence of the counter variable and it showing up in CodeNav.

![image](https://user-images.githubusercontent.com/1820661/136257973-d4007e4c-59e1-41a9-b1f5-3f36a8d1db91.png)

After filtering:
Counter variable is not shown in CodeNav.

![image](https://user-images.githubusercontent.com/1820661/136258172-027cff61-ca06-4b86-9805-ca2348177ce1.png)

**Comment by Brummell67** [comment]
You right, sorry.
I honestly expected the filter to show the selected category, instead hide it.
Thank you.
