### ISSUE TITLE
Crash on mouse click

### ISSUE THREAD

**Issue by Brummell67** [sboulema/CodeNav#106]
Clicking on highlighted label, **only that**, Visual Studio crashes and reboot.
![image](https://user-images.githubusercontent.com/5261273/87842752-34452480-c8af-11ea-9b99-1d8b03034a67.png)

I tried 4-5 times.

![image](https://user-images.githubusercontent.com/5261273/88128529-771c3a80-cbd6-11ea-89f7-98caf9deb295.png)

### Version
Microsoft Visual Studio Community 2019
Versione 16.6.3
VisualStudio.16.Release/16.6.3+30225.117
Microsoft .NET Framework
Versione 4.8.03752

CodeNav   1.0

**Comment by Brummell67** [comment]
I sent crash report to Microsoft:
https://developercommunity.visualstudio.com/comments/1119502/view.html

**Comment by sboulema** [comment]
Crash should be fixed in the next release!

Thanks for reporting :D
