### ISSUE TITLE
No icon when working in "small modus"

### ISSUE THREAD

**Issue by Spoelle** [sboulema/CodeNav#108]
Hello,

a picture can say more than 1000 words...
Small size grouped tool windows
![image](https://user-images.githubusercontent.com/19902865/106582544-63b63880-6544-11eb-8ce4-6649a95caa35.png)

Normal size grouped tool windows
![image](https://user-images.githubusercontent.com/19902865/106582706-94966d80-6544-11eb-905b-c9990582fbf3.png)

**Comment by Ordisoftware** [comment]
Same thing using [VSIconizer](https://github.com/olegtarasov/VSIconizer)
[Issue: Missing icons #2](https://github.com/olegtarasov/VSIconizer/issues/2)

![image](https://user-images.githubusercontent.com/22332878/110258717-51e10e80-7fa4-11eb-8e9b-8209e9cbef5e.png)

**Comment by sboulema** [comment]
It only took 5 months... I added the icon!

Grab the new release!

**Comment by Ordisoftware** [comment]
It works very well, thank you!
