### ISSUE TITLE
Clicking an interface name line crashes Visual Studio.

### ISSUE THREAD

**Issue by HubKing** [sboulema/CodeNav#109]
Clicking the line where I have highlighted in a red rectangle and an arrow crashes VS 2019 every time. This extension is useful, but I think it makes VS crash for various reasons. I do not mind if it sometimes does not work properly, but I want to avoid VS crashing. Could you add a kind of 
"catch all exception" code so that no matter what happens VS would not crash, even if this extension is not working?

![image](https://user-images.githubusercontent.com/10900489/112830464-8476b680-90cd-11eb-82d5-0d8855bafe8c.png)

![image](https://user-images.githubusercontent.com/10900489/112830592-b8ea7280-90cd-11eb-8517-461eb17a1121.png)

**Comment by sboulema** [comment]
Thanks for reporting the crash!

Please try the new release and let me know if that is more stable :)

**Comment by HubKing** [comment]
Thanks. This crash does not happen and clicking the interface name brings the caret to the beginning of the file. That is alright, but if the caret moved to the interface definition, it would have been better.
