### ISSUE TITLE
Code windows do not open at all in Visual Studio 2022 Preview 2.0.

### ISSUE THREAD

**Issue by HTD** [sboulema/CodeNav#113]
I just installed fresh VS 2022 Preview 2.0, then I removed previously installed extension CodeNav 2019 (it just didn't work, VS showed no errors and worked correctly, just no CodeNav panel). Then I installed CodeNav 2022, but now my code files do not open at all. Can it be because I use experimental feature of new icon set? Or maybe it's because something from the previous version of the extension remained in my system?

Or... Forget it, I disabled the extension, restarted VS, enabled the extension, restarted VS, now it works.

**Comment by sboulema** [comment]
Glad to hear you got it working again :D
