### ISSUE TITLE
Document outlining support

### ISSUE THREAD

**Issue by HTD** [sboulema/CodeNav#115]
Not really an issue but suggestion:

It would be super useful if folding some code using those "+/-" icons in editor caused folding / unfolding in CodeNav window.

Also it could work both ways. I found using the CodeNav window more convenient than folding / unfolding in the editor. In my code I have documentation and attributes that take space and make it harder to find the markers.

When we're at it, a nice feature would be "Collapse all / Expand all" icons in CodeNav. It would make working with larger files easier.

**Comment by sboulema** [comment]
Code folding, both ways, already works like that :)
Do you have a sample piece of code where it doesn't work ?

Collapse/Expand all, can be found in the context menu of CodeNav :)

**Comment by HTD** [comment]
Yes, I noticed, the behavior was probably a Visual Studio 2022 Preview bug, because now it works most of the time. When it doesn't restarting VS help. I'll investigate the logs for errors when it breaks.

**Comment by HTD** [comment]
Now it can be closed, I created the new issue when the unexpected behavior is explained in details.
