### ISSUE TITLE
Inherited members support

### ISSUE THREAD

**Issue by HTD** [sboulema/CodeNav#116]
Suggestion:
When a class is derived from an abstract class, it would be nice if I could see the members of the base class. Let's say my class implements the abstract base class. Visual Studio has the option `Go to base` - that should happen if the current code doesn't have it's own override and just inherits a member from the abstract (or even a standard) class. Since the functionality is already built in Visual Studio, it probably can be implemented into extension. For practical reason - either only direct ancestor members should be used, or the first ancestor that has the member defined in its own code. With the exception of Object, those would only clutter the view.

**Comment by sboulema** [comment]
Grab the new release! 🚀

**Comment by HTD** [comment]
In the new release: some members from base abstract class are shown (no events), but the other class file is not opened in the editor. Instead VS goes to correct line in incorrect file.

I have an `EndPoint` abstract class that is a base class for both `Client` and `Server` classes. It provides `MessageReceived` event, so the `Server` and `Client` doesn't have to. The `Server` class provides `ClientConnected` event, because that's what only `Server` needs. So it would be super cool if I could see in CodeNav all events I have in `Server` class (both direct and inherited). So `ClientConnected` and `MessageReceived` next to each other. `MessageReceived` is inherited from `Endpoint`, `ClientConnected` is implemented directly. Now - one extra thing should happen when the inherited member is clicked. The base class file should be opened. So I click on `ClientConnected` - it works as it does now - the VS just goes to the event in code. When I click on `MessageReceived` (currently not shown) - it should open the `EndPoint` class and go to the member.

**Comment by HTD** [comment]
One more thing - it would be great if inherited members view would be optional, on big classes the view gets messy.

**Comment by sboulema** [comment]
Working on fixing the bugs you reported!

You can opt out of showing the base class inherited members, by using the filter window and setting kind "baseclass" to invisible.

**Comment by sboulema** [comment]
Grab the new release! :rocket:
