### ISSUE TITLE
Standalone CodeNav window shows structure of 'previously active document'

### ISSUE THREAD

**Issue by JanCervak** [sboulema/CodeNav#119]
CodeNav standalone window content seems to be "one step behind" the active document on a document change. This happens when the new active document is selected from the already opened ones. This issue affects document selection by 

- clicking from 'Editor document tabs'
- using ctrl-tab shortcut
- selection in the 'Solution explorer' 
- 'Go To dialog' usage
(the list might be incomplete, these are the ways I'm using)

That means the previously active document's code structure is being shown until explicit refresh (CodeNav window button).

For a "not opened document" selected from 'Solution explorer' or using 'Go To dialog' the code structure is refreshed correctly.

CodeNav 8.3.748
VS 2019 16.11.2
[extension_exception.txt](https://github.com/sboulema/CodeNav/files/7122047/extension_exception.txt)

**Comment by sboulema** [comment]
Grab the new release! 🚀

**Comment by JanCervak** [comment]
Works fine now. Thank you.
