### ISSUE TITLE
A couple of enhancement requests regarding current method

### ISSUE THREAD

**Issue by HubKing** [sboulema/CodeNav#12]
1. It would be helpful if there is option to scroll automatically to the current method when it is outside the visible portion.

2. The blue highlight is not easily recognisable, at least on my monitor.  It needs to be darker under the Light theme, and lighter under the Dark theme. 
Below are comparisons with a similar commercial extension. I have assigned the same fonts to both of them. The left is CodeNav, and the right is SuperCharger.

    ![light](https://cloud.githubusercontent.com/assets/10900489/23291433/d28dfa58-fa9b-11e6-823a-20d283cc3cad.PNG)
    ![dark](https://cloud.githubusercontent.com/assets/10900489/23291434/d293e0f8-fa9b-11e6-86e0-8ad566bfb81d.PNG)

**Comment by sboulema** [comment]
1. This has been bugging me for a while now, Haven't found a way to implement this feature. Will try to come up with a solution.

2. Highlighting has been improved in the next version :)

**Comment by sboulema** [comment]
1. is now fixed in the upcoming release :D

**Comment by HubKing** [comment]
I am not sure if this is an intended behaviour or a bug, but to me it looks more like a bug.

In the latest version, under Dark theme, whenever a method gets the cursor, that method in CodeNav gets gray background and the gray background persists even if the cursor has moved to another method. After moving the cursor through lots of methods, all of those methods now have gray background.

**Comment by sboulema** [comment]
Stupid mistake >_< 
Will be fixed in the upcoming 1.9 release
