### ISSUE TITLE
Content load timing issue

### ISSUE THREAD

**Issue by HTD** [sboulema/CodeNav#120]
The loading of the code structure happens too early, not properly synchronized with the proper ready state of VS2022.

This leads to following issues:
- The CodeNav window is empty after opening the file (this happens randomly, rather rarely).
- The CodeNav window displays invalid outlining, so all items are expanded in the CodeNav, but in the editor all items are collapsed. Or any state in between. When there is a mismatch in outlining - the outlining is not synchronized until the same state is achieved on both sides.

Both issues (with empty window and outlining) are temporarily fixed when the "Reload" button of the CodeNav window is pressed.

Tested on Visual Studo 2022 Preview 3.

**Comment by sboulema** [comment]
Grab the new release! 🚀

**Comment by HTD** [comment]
Is it a bird, is it a plane? No, it's Flash ;) The rest of the Visual Studio lags behind ;) And of course it works.
