### ISSUE TITLE
CodeNav makes VS hang with 100% CPU use when refactoring used on big solution.

### ISSUE THREAD

**Issue by HTD** [sboulema/CodeNav#128]
To reproduce try to load any big solution containing like 8 or more C# projects. My specific solution has 8 C# .NET 6.0 projects in it.

Then do several refactorings like changing a class name or a property name somewhere.

In my case - each refactoring causes considerable VS slowdown, up to CPU halting from overheating. When the VS enter the slowdown state - it does not recover from it, the CPU usage drops slightly, but each key press or mouse click causes it to choke again. The only way out is out, I have to restart VS.

Then I disabled CodeNav and tried doing the refactoring again. No slowdowns, everything works stable.

I suspect the code refactoring cause triggering some events that CodeNav tries to handle and that in turn causes system overloading.

To investigate try to check which event handlers fire on refactoring.

**Comment by sboulema** [comment]
Related to #94

**Comment by sboulema** [comment]
Try the new release 🚀 ! 
Please let me know if that improves the performance...

**Comment by HTD** [comment]
It's blazing fast now. It actually works much faster than Supercharger I was using for a while. Thanks!

**Comment by HTD** [comment]
Oops, it's back. Now it works faster, especially at the start, but after some time - it gets slower and slower. Not to the point of completely freezing the VS, but there is a significant increase in CPU usage over time. It's noticeable even in relatively small solution, like 3 projects and about 1000 LOC total in all files.

It seems like each subsequent keypress adds to the slowdown.

**Comment by sboulema** [comment]
Oh no! 

Could you try disabling highlight and history indicators in CodeNav settings. Restart VS. 

If the slowdown is less or gone I know which sections of code are the culprit.

Thanks in advance!

**Comment by HTD** [comment]
OK, but that will take some time, since this issue doesn't appear on fresh editors. I tried to do some dummy editing on files, but nothing happened. I mean no slowdown yet. I have a lot of work today, so sooner or later the issue should trigger. It takes like 10 to 20 minutes of various editing and refactoring to kick in. I'm on it.

**Comment by HTD** [comment]
UPDATE: VS crashed after refactoring. IDK if it's related, but it's very likely. I use code analyzers a lot, when I find any analyzer complaint I often choose to fix it solution-wide, so it refactors dozens of files in one run, but that causes freezes when CodeNav is enabled.

I disabled history indicators, restarted VS and tried to do the rest of the refactoring from the analyzers. For now - no slowdown yet. It probably helped. You could trigger massive changes by switching file scoped namespaces for entire big solution. This change will affect each file, and undoing that when the error is present should make VS hang for a couple of minutes or crash. Now (when history indicators disabled) it seems to work, refactoring just go without choking VS.

**Comment by HTD** [comment]
UPDATE: Problem still occurs. After some editing (not refactoring this time) VS died. 100% CPU usage, and practically every keypress causes it to take 100% CPU load, I have no option but to restart VS to continue working.

I think the only solution to fix this problem in CodeNav it to implement some overload detection. If it receives a single event - like a file opened, closed, changed - it should handle it. But if it receives multiple events in less than a second - something bad is happening.

The most peculiar about this issue is it grows over time. It accumulates. In fresh editor everything works, there is no difference with or without CodeNav. But then after like 15 minutes of coding VS is becoming slightly slower and it gets slower until it becomes completely unresponsive.

**Comment by sboulema** [comment]
Thanks for all the debugging and reporting! Sounds like it's memory leaking somewhere. 
Will check if I can cleanup and optimize the event handling.

**Comment by HTD** [comment]
Any luck with that thing? I miss the CodeNav, the Supercharger is not as cool ;) It doesn't mark interface implementations as neat as CodeNav does.

**Comment by sboulema** [comment]
Sorry, life getting in the way of coding. Issue is not forgotten but stil in the Todo list...

**Comment by sboulema** [comment]
Try the new release! 🚀

**Comment by HTD** [comment]
So far so good. I'm still testing.

**Comment by HTD** [comment]
OK, after a few days of testing - it seems to work fine. No lags.
