### ISSUE TITLE
Structure is not shown for a source code reconstructed from metadata

### ISSUE THREAD

**Issue by HubKing** [sboulema/CodeNav#13]
If you try to jump to the definition of a method that is inside of a DLL, Visual Studio shows the reconstructed source code from its metadata. The structure is currently not shown, but it would be helpful it is shown.

Below is a comparison with "SuperCharger" (on the right), when navigated to a BCL class.
![metadata](https://cloud.githubusercontent.com/assets/10900489/23291687/6f747026-fa9d-11e6-80f5-61b2ad06563d.PNG)

**Comment by sboulema** [comment]
Fixed in the upcoming 1.7 release :D
