### ISSUE TITLE
C# 9 records are not recognized by CodeNav

### ISSUE THREAD

**Issue by Bergam64** [sboulema/CodeNav#133]
Hello Samir,

CodeNav doesn't recognize C# 9 records.

- In a C# file containing a `class` and a `record`, only the `class` is displayed in CodeNav.
- A C# file containing only a `record` doesn't display CodeNav at all. E.g.

  ```csharp
  namespace SomeNamespace
  {
      /// <summary>
      /// Some comment.
      /// </summary>
      public record MyModel(string Param1, object? Param2);
  }
  ```

Please add support for records.

CodeNav 2019 v8.8.32 running on VS 2019 v16.11.4.

Best regards,
Didier

**Comment by sboulema** [comment]
Good enhancement!

Should be to difficult to add :)

**Comment by Bergam64** [comment]
Hello Samir,

I'm using the latest version (8.9.34 on VS 2019 v16.11.4), but it still doesn't recognize records. No apparent change on that level since v8.8.32.

Please investigate.

Thanks in advance,
Didier

**Comment by sboulema** [comment]
Could you please share a source file?

It looks to be working for me with my simple .cs file: 
![image](https://user-images.githubusercontent.com/1820661/155299081-160a0b0a-39a3-4cf8-96dc-6d454d622e4f.png)

**Comment by Bergam64** [comment]
Hello Samir,

Here's one:
```csharp
using Elsa.Activities.Http.Models;

namespace ElsaWorkflows.Models
{
    /// <summary>
    /// This model represents the 2 parts of the response of a <see cref="Elsa.Activities.Http.SendHttpRequest"/>
    /// activity.
    /// </summary>
    public record SendHttpRequestResponse(HttpResponseModel Model, object? Body);
}
```

Note: if you need this file to be compilable, install NuGet package `Elsa` 2.3 or later.

Best regards,
Didier

**Comment by Bergam64** [comment]
My previous post was about v8.9.35.
I've just upgraded to v8.9.38 and the problem is still present.

**Comment by sboulema** [comment]
Could you please test if this version fixes the problem?

Records work in the VS 2022 version of CodeNav, but getting it to work in the VS 2019 version might create some weird nuget package errors.

[CodeNav.VS2019.zip](https://github.com/sboulema/CodeNav/files/8140361/CodeNav.VS2019.zip)
