### ISSUE TITLE
Regression in CodeNav v8.9.38: #region directives are ignored in NUnit test classes (C#)

### ISSUE THREAD

**Issue by Bergam64** [sboulema/CodeNav#137]
Hello Samir,

CodeNav v8.9.38 ignores `#region` directives in NUnit test classes (C#):

![image](https://user-images.githubusercontent.com/29800159/155696587-9065c5e4-dfc6-490f-88a8-7fcd7a3632f8.png)

But not in other C# classes.

This was not the case with the previous version I was using (v8.9.35).

Please investigate.

Best regards,
Didier

**Comment by sboulema** [comment]
Thanks for reporting!

Should be fixed in the new release (8.9.40)

**Comment by Bergam64** [comment]
Nice response time, Samir!

Yes, the bug appetas to be fixed. Good work!

**Comment by Bergam64** [comment]
appears*
