### ISSUE TITLE
[Feature request] Expand any Region in Codenav Panel on Single\Double Click

### ISSUE THREAD

**Issue by MayMih** [sboulema/CodeNav#141]
It's rather boaring to aim and click on [+] icon every time I want to expand a region on the Code Nav panel.

It would be great If I can just double click on the region header to Expand it. 
Or it can be implemented as the Option - what to do on Single/Double Click on the region: "Go To Definition" or "Expand the region".

**Comment by sboulema** [comment]
Thanks for the suggestion! Grab the new release 🚀
