### ISSUE TITLE
Double-clicking a method in CodeNav sometimes crashes Visual Studio 2017

### ISSUE THREAD

**Issue by HubKing** [sboulema/CodeNav#15]
I do not the exact condition, but at least two times, when I double-clicked a method in CodeNav crashed Visual Studio 2017. I am sorry that I cannot provide the exact condition, but if possible, please examine the code for possible exceptions.

In addition, I suspect that CodeNav caused Visual Studio to hang for several seconds on several occasions. I remember those happened while I was typing in the code editor, so it is not 100% that they were caused by CodeNav, but I had not experienced such long hang while typing before installing CodeNav.

**Comment by sboulema** [comment]
I have seen the double-click crash myself as well. I haven't been able to fix it completely yet.
Will investigate this and the typing slowness more and try to add more exception handling!

**Comment by sboulema** [comment]
Should be way better now.

A lot has been improved in mapping. Please reopen if you still come across this bug
