### ISSUE TITLE
Feature Request: Region Sync & Collapse All

### ISSUE THREAD

**Issue by TrickUK** [sboulema/CodeNav#17]
Excellent alternative for CodeMap/Supercharger.tools, just missing this one feature to make it complete for me!

- Sync Region expand/collapse.
- Add "Collapse All" button to CodeNav.

**Comment by sboulema** [comment]
Thanks for the suggestion!

Added in the new 2.0 release :D

**Comment by TrickUK** [comment]
Just updated to version 2.0; very cool indeed!  Thanks for adding the feature :-)
