### ISSUE TITLE
"internal delegate" crashes Visual Studio

### ISSUE THREAD

**Issue by HubKing** [sboulema/CodeNav#18]
Steps to reproduce:
1. Type `internal delegate void Test(int id);`
2. Press Ctrl + S to save it.

System.IO.IOException occurred
  Message=Cannot locate resource 'icons/delegate/delegateprotect_16x.xaml'.

**Comment by sboulema** [comment]
Stupid mistake. Fixed in the upcoming 2.0 release :)
