### ISSUE TITLE
Essential configuration.

### ISSUE THREAD

**Issue by HTD** [sboulema/CodeNav#2]
Please add basic configuration like displaying on the right side or hiding the control. It would be nice if the user could choose which members are displayed: public, protected, private, static, fields, properties, methods, events. Just a simple filter looking exactly like the one shown by VS 2017 when auto-complete for C# kicks in.

**Comment by sboulema** [comment]
With the upcoming 1.3 version it will have the following features:
- Double-click the splitter to hide the control
- Options screen to change sides
- Filter screen to change which elements are shown
