### ISSUE TITLE
Navigating to a class inside a DLL crashes Visual Studio 2017

### ISSUE THREAD

**Issue by HubKing** [sboulema/CodeNav#21]
**Steps to reproduce:**
1. Locate the cursor on a class inside a DLL, such as the `Form` of the following code.

        public partial class Form1 : Form

2. Press "F12" to navigate to Form.

**The exception message is,**

    System.NullReferenceException: 'Object reference not set to an instance of an object.'

**Comment by sboulema** [comment]
Fixed in the new release!
