### ISSUE TITLE
Add parser for cases in switch statement

### ISSUE THREAD

**Issue by mrbostjo** [sboulema/CodeNav#23]
Thank you for your great addon, but i have suggestions for improvement:

It would be great if you added parsing of switch statement in a method and all statement's cases, it would make navigating through big monster switches, which are not so uncommon much  easier ( at least i think so ;) ).

I'd also suggest to add decoration for CodeNav window, so it could be used as tabbed document, be pinned and be auto hidable as are other information windoes in visual studio.

**Comment by sboulema** [comment]
Your welcome!

Will look into switch parsing :)

You can find the CodeNav toolwindow at View -> Other Windows -> CodeNav. 
This window can be docked anywhere in visual studio. Is that maybe what you are after?

**Comment by mrbostjo** [comment]
Ah yes, that's what i was looking for.

 Thank you very much.

**Comment by sboulema** [comment]
Added switch statement parsing in the new 2.4 release!
You can enable showing switch statements in the filter options
