### ISSUE TITLE
Issue with regions

### ISSUE THREAD

**Issue by silverferrum** [sboulema/CodeNav#24]
Hi! I have found an issue with regions.

![image](https://cloud.githubusercontent.com/assets/19478181/26274036/6754d880-3d47-11e7-8721-d329f39f6c12.png)

Test2 must be in \#R1 region on the map.

Class for test
```
public class Class1
{
    #region R1
    public void Test1()
    {

        #region R11
        int i1 = 0;
        #endregion

        #region R12
        int i2 = 0;
        #endregion

        #region R13
        int i3 = 0;
        #endregion

        #region R14
        int i4 = 0;
        #endregion
    }

    public void Test2()
    {

    }

    #endregion
}
```

**Comment by sboulema** [comment]
My guess is that the region within a region is screwing with my parsing logic. 
Thanks for the clear example and sample code, will look into it!

**Comment by sboulema** [comment]
Should be fixed in the new release!

![screenshot](http://i.imgur.com/9iT4u9v.png)

**Comment by silverferrum** [comment]
Great! Thank you!
