### ISSUE TITLE
crashes 2017 rc when clicking on a method name

### ISSUE THREAD

**Issue by bradtwurst** [sboulema/CodeNav#3]
2017 rc crashes when clicking on a method name.

**Comment by sboulema** [comment]
Can you provide a bit more information? Maybe a file that I can use to reproduce it? Will add more null checking to that part of the code next version.

**Comment by bradtwurst** [comment]
sorry for the lack of detail...

The solution is fairly large, and I don't know if that is the main cause.

I will investigate and try out different situations and see what I can provide.

**Comment by sboulema** [comment]
Thank you very much! 

Could be a couple of things, complicated file structure, timing issue in selecting items, selecting quickly after opening a new tab...

As said will add more failsafes and you can try the debug build for next release, that will output some more info...

**Comment by sboulema** [comment]
Thanks for the steps to reproduce!

Try the new 1.3 release (https://github.com/sboulema/CodeNav/releases/tag/v1.3)
Was unable to reproduce the crash with the new version :)
