### ISSUE TITLE
private properties showing as [Public] upon mouse hover

### ISSUE THREAD

**Issue by Troncho** [sboulema/CodeNav#43]
Hi, I've found two minor issues:

**1.** If I declare:
`int LineId { get; set; }`

On the [CodeNav] window, upon mouse hover, the extended info shows as:
`Public int LineId LineId {get; set; }`

**2.** If I add the [private] keyword in front like:
`private int LineId { get; set; }`

[LineId] disappears from the [CodeNav] window.

------------------------------
On both cases, I think they could appear on [CodeNav] window as [Private] on mouse hover.

Thanks!

**Comment by sboulema** [comment]
The small things also matter!

New version (3.6) released :)

**Comment by Troncho** [comment]
Good! The update works fine! Thanks 😊

Have a nice week.

Marcelo Mejail
