### ISSUE TITLE
Refresh doesn't take into account selected sort type consistently

### ISSUE THREAD

**Issue by benfarrall** [sboulema/CodeNav#44]
Refreshing the nav works by showing any new code, but it looks like it isn't applying the selected sort properly. I have to click an option again afterwards e.g "Sort by file order".

**Comment by sboulema** [comment]
Thanks for reporting this! Should be fixed in the next release :)

**Comment by benfarrall** [comment]
Thanks for fixing it so quickly! The extension is excellent; All the important parts of CodeMap, but much lighter.
