### ISSUE TITLE
Feature Request: Private Fields

### ISSUE THREAD

**Issue by benfarrall** [sboulema/CodeNav#45]
Is there any plan to make private fields visible or is there some limitation that prevents it?

**Comment by sboulema** [comment]
Private fields are now also visible!
There was no limitation other than my personal preference... So the filter options are now also improved so it is easier to select what CodeNav will show

**Comment by benfarrall** [comment]
I can now see private fields but the new filter options is acting strange. It now shows switch statements, which is great but if I try to filter out the switch section, it's also filtering out the method above it. No combination of order or access level I set seems to only show the method without the switch statement inside.

**Comment by sboulema** [comment]
Sorry! Should be fixed in the new release.

**Comment by benfarrall** [comment]
Cheers! Appreciate the fast fixes!
