### ISSUE TITLE
new 4.0 version make VS 2017 to crash

### ISSUE THREAD

**Issue by pleveill** [sboulema/CodeNav#47]
To reproduce it:
Previously install and 3.x version, use it and then update to the 4. version.
Open a fresh VS session (VS 15.4.4)
Open any c# file, (even via new file VS menu)
The VS crash (open a small dialog with an error msg and clicking ok shutdown VS)

Goes back to 3.9.157 solve the problem

**Comment by pleveill** [comment]
Message is : Something bad happened, closing application...

**Comment by sboulema** [comment]
Have you tried installing the debug build of CodeNav and see if it gives any error: https://github.com/sboulema/CodeNav#debugging

Is there anything in the Visual Studio activity log perhaps: https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log

Interested into what is exactly what is causing your crash...

**Comment by dwenegar** [comment]
Same problem here and `FilterRules` is `null` at this line for me.

https://github.com/sboulema/CodeNav/blob/b8986cdafe6a3324943e1505eca0d628d177147c/CodeNav/Helpers/VisibilityHelper.cs#L93

**Comment by sboulema** [comment]
Thank you very much. Fixing the bug now!

**Comment by pleveill** [comment]
>  Have you tried installing the debug build of CodeNav and see if it gives any error: 
Not yet. Is this still necessary ?

Thanks for this very quick response and correction

**Comment by sboulema** [comment]
Grab the new release!
