### ISSUE TITLE
Outlining

### ISSUE THREAD

**Issue by OlekRia** [sboulema/CodeNav#49]
It would be great if extensions outlining repeats code outlining, More or less.

**Comment by sboulema** [comment]
Care to explain a bit more? I am not quite understanding your suggestion?!

**Comment by OlekRia** [comment]
So, You may expand or outline your code. 
We use Ctrl+M+M Ctrl+M+O Ctrl+M+L very often in our code.
And a file might be really huge. Not only source code, but your map is also !. It would be great, if my region for example outlined it should be outlined in your map.

Also, I must note: Switch expanding is ugly :( . I would prefer to remove it from Navigation Map.

**Comment by sboulema** [comment]
It is already possible to hide the Switch statements, see below:

![HideSwitch](https://i.imgur.com/mD7lad9.png)

**Comment by OlekRia** [comment]
Oh, sorry. I thought it should be in filters. Sorry for misunderstood.
