### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by emina-saric** [sboulema/CodeNav#5]
So I installed this, and... nothing. I thought a navigation was supposed to appear on left side of VS?

VS version: 2015 Enterprise Update 3.

**Comment by sboulema** [comment]
Please try this new version that should fix compatibility

[CodeNav_1.4.25_debug.vsix.zip](https://github.com/sboulema/CodeNav/files/750961/CodeNav_1.4.25_debug.vsix.zip)

**Comment by emina-saric** [comment]
Oh, here it is! Thank you.
