### ISSUE TITLE
Null AsClause

### ISSUE THREAD

**Issue by Ifn00b** [sboulema/CodeNav#54]
In _CodeNav.dll!CodeNav.Mappers.PropertyMapper.MapProperty(Microsoft.CodeAnalysis.VisualBasic.Syntax.PropertyBlockSyntax member, CodeNav.CodeViewUserControl control, Microsoft.CodeAnalysis.SemanticModel semanticModel) Line 50	C#_

**member.PropertyStatement.AsClause**

Code:
Public Property _Titulo1$

(You can use $ instead of ' As String')

**Comment by sboulema** [comment]
Thanks for submitting the issue and thanks for the clear description!

Please try the new release (4.2.179)

**Comment by Ifn00b** [comment]
Works perfectly 
**Thanks!**

**Comment by sboulema** [comment]
Good to hear!
