### ISSUE TITLE
Where is the MarginSide property stored?

### ISSUE THREAD

**Issue by Spoelle** [sboulema/CodeNav#57]
I've set this property in the settings dialog to "None" (so not left and not right) and now when I want CodeNav to show (VS menu ->View-Other Windows-CodeNav) then VS hangs and keeps hanging; CodeNav is not show and no output is generated with the debug version of the extension.
I've tried to uninstall the extension but when reïnstall it seems that the MarginSide setting is still somewhere kept around. I would like to change it manually to Left again.
Thanks in advance!
versions : 
tested with : CodeNav_4.2.184.vsix and CodeNav_4.2.184_Debug.vsix
VS version = 15.6.5
.NET Framework version = 4.7.02558

**Comment by sboulema** [comment]
Confirmed, I am able to reproduce will look into why it is making VS crash :(

**Comment by Spoelle** [comment]
Works perfect !! Thanks for such quick solution.
