### ISSUE TITLE
Feature request - highlight / mark

### ISSUE THREAD

**Issue by Spoelle** [sboulema/CodeNav#58]
Would be nice to have the possibility to highlight or (book)mark things so you quickly have a view on witch methods you are working on or for example the methods with bugs. For this you can give a popup on rightclick on a method in CodeNav window where you can choose a color. This color will be the background color (! Foreground color change when needed for example light background =>change forerground color to black).
Another possibility is to work with signs that you put in front of the method in CodeNav window.

Thanks for this already good working extension!

![image](https://user-images.githubusercontent.com/19902865/40537897-6793006e-6010-11e8-9f56-c122a69ac2fe.png)

**Comment by sboulema** [comment]
Good suggestion!

Try the just newly released version: https://github.com/sboulema/CodeNav/releases/tag/v4.3.188

**Comment by Spoelle** [comment]
Nice to see that you react so quickly to proposals or comments!
I've installed the latest version and have the following comments:

First of all, smooth implementation already!

In terms of design I have 2 comments:
- now only preset colors, I like to choose my colors myself  :-)
- I find it more readable when the background color goes through completely (see image below)

![image](https://user-images.githubusercontent.com/19902865/40774632-65e325e0-64c6-11e8-9722-d2af006d8801.png)


Another remark is to store these bookmarks for later use, I mean when I close my solution at the end of the day maybe my work isn't finished yet and when I reopen the solution next day it would be nice to see my bookmarks again. Maybe store these bookmarks in a file in the folder with the ".sln" file?


Another suggestion. Have the possibility to filter on Bookmarks, I mean show only bookmarked items.


Keep up the good work, thanks, and I'm always willing to test things out.

**Comment by sboulema** [comment]
"You give them a finger and they take your whole hand" 👍 

Good suggestions!

- custom colors, didn't want to implement it on the first go, will look into it, not sure how to fit this into the gui
- full width bookmark color, just finishing implementing in a new version
- filtering on bookmarks, just finished implementing in a new version
- saving bookmarks, will look into it

Thanks for the suggestions and thanks for testing :)

**Comment by sboulema** [comment]
Please try the new release: https://github.com/sboulema/CodeNav/releases/tag/v4.4.194

**Comment by Spoelle** [comment]
Not usable version....
When I want to set a bookmark, on the click on a color =>VS crashes.
I also noticed a few time that VS crashes when using CodeNav window. Tested with CodeNav uninstalled =>ok. Then tested with CodeNav installed but not active =>ok. CodeNav active =>once or twice a day spontaneous crash VS.

**Comment by sboulema** [comment]
Having a hard time reproducing the crashes. Please try the new release: https://github.com/sboulema/CodeNav/releases/tag/v4.4.195. Hopefully the improved logging will shed some light on the problem.

**Comment by Spoelle** [comment]
Problem still exact the same, sorry.

**Comment by sboulema** [comment]
That stacktrace was really helpful!

New release: https://github.com/sboulema/CodeNav/releases/tag/v4.4.196

**Comment by Spoelle** [comment]
Stable now, good work!

Four remarks  :-)
- the popup dialog is not closing after choosing a color bookmark ->rightclick a method, click color, then you need to click "somewhere else" to close the dialog. To me it looks better to close the dialog automatically.

- when changing a bookmark style, the already bookmarked methods keep there old style, they should get the new style automatically. ->Mark a method with red background ->change bookmark style of red into orange =>my red marked method should change into orange.

- change bookmark style from red into orange ->close VS ->open same VS solution ->now the red bookmark style is back red while you changed it before into orange. I think is better to keep the orange style, maybe per solution.

- the "filter on bookmarks" "checkbox" is now in the popup dialog. I would prefer to have this in a button on top of CodeNav for example next to the "Sort by name" button. This is faster.

Many thanks already for this nice extension. I have to work in VB6 (old VS) now so I can not do intensive testing now but I will take some time to do small tests when you have new versions.

**Comment by sboulema** [comment]
New release is available: https://github.com/sboulema/CodeNav/releases/tag/v4.4.200

**Comment by sboulema** [comment]
Great to hear!
