### ISSUE TITLE
VB Select Case statement is represented as "Switch".

### ISSUE THREAD

**Issue by Spoelle** [sboulema/CodeNav#59]
Hello, I've noticed in VB code files that the Select Case statement is represented apart but with the word "Switch". Personally, I do not see the added value of this, a Select Case is "just" a piece of code, not? For me, this should not be visible in CodeNav. If the intention was to show this, would it be possible to switch this on or off via the options? Thanks.

![image](https://user-images.githubusercontent.com/19902865/40712422-00735f90-63fe-11e8-8961-ac805d8986d4.png)

**Comment by sboulema** [comment]
You can already filter items showing up in CodeNav!

https://github.com/sboulema/CodeNav/wiki/Flitering

**Comment by Spoelle** [comment]
OK, perfect!
