### ISSUE TITLE
CodeNav not loading file structure on startup

### ISSUE THREAD

**Issue by Spoelle** [sboulema/CodeNav#60]
Very minor not to important issue but still...

Open solution with code files open from previous run; cursor is blinking in code file but :
![image](https://user-images.githubusercontent.com/19902865/40827024-bc8012ee-657c-11e8-9167-7e54f6a0a2bf.png)

Start editing the active file
![image](https://user-images.githubusercontent.com/19902865/40827036-c484df7e-657c-11e8-8f52-c8922a0835ef.png)

Click in CodeNav window
![image](https://user-images.githubusercontent.com/19902865/40827051-cb4adb2e-657c-11e8-9195-81792c535b92.png)

Only after putting focus on "something" else in Visual Studio and put focus back on de code file (mouse click), then CodeNav loads the file structure

**Comment by sboulema** [comment]
Please try the new release: https://github.com/sboulema/CodeNav/releases/tag/v4.4.194

**Comment by Spoelle** [comment]
Tested
Start VS with tabs with open VB files from previous run and cursor blinking in file => CodeNav says "Waiting for active...."
Start editing =>no change in CodeNav
Change tab to another VB file =>ok =>file structure is loaded

**Comment by Spoelle** [comment]
I'm now on a new much quicker system with WIN10 and all is working fine now; refresh is automaticly done. Thanks for this nice extension ! Issue closed
