### ISSUE TITLE
Improve the background for  the active item

### ISSUE THREAD

**Issue by Ifn00b** [sboulema/CodeNav#61]
The background is it's too light
i can configure it?

![captura](https://user-images.githubusercontent.com/36337223/40998897-781a1f56-6909-11e8-847e-5ed6be78f5f5.PNG)

**Comment by sboulema** [comment]
Please try the new release: https://github.com/sboulema/CodeNav/releases/tag/v4.4.195

**Comment by Ifn00b** [comment]
Very very very thanks :)
I love you.
