### ISSUE TITLE
Decrease  item alpha if it is private 

### ISSUE THREAD

**Issue by Ifn00b** [sboulema/CodeNav#67]
I would an improvement like this

For example: 
![sin titulo-1 copia](https://user-images.githubusercontent.com/36337223/46579592-3ceba400-ca15-11e8-9cfc-04786b2ae111.png)

Thanks!.

**Comment by sboulema** [comment]
Grab the new release!

Read https://github.com/sboulema/CodeNav/wiki/Filtering on how to use the new filter option

**Comment by Ifn00b** [comment]
OMG! I love you THANKS!
