### ISSUE TITLE
Location of the CodeNav.json

### ISSUE THREAD

**Issue by silverferrum** [sboulema/CodeNav#68]
Could you put CodeNav.json file into .vs folder, because it appears in git repo so I should every time to unstage it to prevent uploading into repo.

![image](https://user-images.githubusercontent.com/19478181/47007535-2645fb00-d141-11e8-9dc4-76c1fdfaa718.png)

**Comment by sboulema** [comment]
Grab the new release!

**Comment by silverferrum** [comment]
Thank you very much!
