### ISSUE TITLE
CodeNav crashes VS 2017 when navigating to C# from a xaml file

### ISSUE THREAD

**Issue by Bergam64** [sboulema/CodeNav#69]
Hello Samir,

first I'd like to thank you for your continued commitment to improve CodeNav!

I'm the guy who reported issue #26 a long time ago, and it seems a similar issue is back. I've installed the latest CodeNav version (4.8.270), but it crashes VS 2017 (v15.8.7) when navigating to the C# code from a xaml file. For you to easily reproduce the issue, I've attached the same repro solution I had attached to issue #26.

[CodeNavCrash1.zip](https://github.com/sboulema/CodeNav/files/2509257/CodeNavCrash1.zip)

Open the file "MainWindow.xaml" in VS. For each of the following scenarios, VS will crash:
1) Click anywhere in the word "MyViewModel" on line 8 and press F12 (Go to Definition).
2) Click anywhere in the word "Greetings" on line 11 and press F12.

I suspect that, in these scenarios, CodeNav is trying to interact with the UI from a non-UI thread. If that's the case, you may want to consider rewriting your code with the async/await pattern instead of using older technologies (like BackgroundWorker), to make your life easier.

Please investigate and fix.

Thanks in advance,
Didier Prgomet

**Comment by sboulema** [comment]
Thanks for re-reporting the bug!

Grab the new release, backgroundworker is now refactored to async/await, thanks for pushing me into that refactor that I should have done back then ;)

Greetings,
Samir
