### ISSUE TITLE
Version 5.0.276 Doesn't install on VS 2017

### ISSUE THREAD

**Issue by Timestein** [sboulema/CodeNav#71]
The end of the log has this:

01/11/2018 10:38:11 - Skipping 'C:\Users\boazd\AppData\Local\Microsoft SDKs' as it doesn't exist
01/11/2018 10:38:11 - Uninstalling 'CodeNav', version 5.0.276.
01/11/2018 10:38:12 - Successfully uninstalled CodeNav.

I reverted back to 4.5 but would love to use the new version.

Thanks!

**Comment by sboulema** [comment]
Hey,

Which version number and edition of Visual Studio 2017 are you running?
Can you send me the full installation log?

Installation works on my machine, lets try to find out if there is a hidden missing depency.

Greetings,

Samir

**Comment by Timestein** [comment]
Hi Samir,

Originally it crashed cause I didn't have the Microsoft SDK installed (first log).

I then created an empty directory in the path it was searching. Still crashed (second log).

Love your product. Can't think of coding without it.

Thanks,

Boaz Davidoff
Senior Software Engineer
Landa Digital Printing

[Logo]

Mobile: +972-52-680-3604
Tel/Fax:  +972-77-344-4837
boaz.davidoff@landa-corp.com<mailto:boaz.davidoff@landa-corp.com>
www.landanano.com<http://www.landanano.com>

**Comment by Timestein** [comment]
[cid:image002.png@01D471DF.FB0E96B0]

Boaz Davidoff
Senior Software Engineer
Landa Digital Printing

[Logo]

Mobile: +972-52-680-3604
Tel/Fax:  +972-77-344-4837
boaz.davidoff@landa-corp.com<mailto:boaz.davidoff@landa-corp.com>
www.landanano.com<http://www.landanano.com>

**Comment by sboulema** [comment]
Turned out to be related to the switch to PackageReferences and meta sdk package. 
https://blogs.msdn.microsoft.com/visualstudio/2018/10/10/simplify-extension-development-with-packagereference-and-the-vssdk-meta-package/

Fixed in the new release.

**Comment by Timestein** [comment]
Haven't done a VS Extension yet.

Looks like great fun!

Boaz Davidoff
Senior Software Engineer
Landa Digital Printing

[Logo]

Mobile: +972-52-680-3604
Tel/Fax:  +972-77-344-4837
boaz.davidoff@landa-corp.com<mailto:boaz.davidoff@landa-corp.com>
www.landanano.com<http://www.landanano.com>
