### ISSUE TITLE
Thanks !!

### ISSUE THREAD

**Issue by Spoelle** [sboulema/CodeNav#72]
Last months I had constantly crashes without any clue why, not reproducible... so I skipped a few version but I still was following the project. I was interested in the fact that there was refactoring from backgroundworker to async/await (issue #69) and therefore I installed version CodeNav_5.0.279.
After 2 days working with Codenav in VS2017 Professional, no more crashes, everything is working fine. Therefore A big thank you for your work!

**Comment by sboulema** [comment]
Thanks for the kind words and the continued interest!
