### ISSUE TITLE
Auto highlight causes significant delay in editor

### ISSUE THREAD

**Issue by 2mas** [sboulema/CodeNav#75]
Hi and thanks for a very good extension! 
I started to experience delays in my editor when typing or moving the cursor, this seems to be caused by the auto-highlight event that has to do quite alot of processing when the current file has a large amount of methods in it.

Consider adding an option to disable this featue, I'll send a pull-request along with this

**Comment by sboulema** [comment]
Thanks for reporting and thanks for the pull request!

Grab the new release :)

**Comment by 2mas** [comment]
Awesome, thanks!
