### ISSUE TITLE
Defaulting to always collapsed

### ISSUE THREAD

**Issue by codinglifestyle** [sboulema/CodeNav#77]
I think something regressed where the navigation is now always collapsed by default.  Even if I expand a class if I view another tab and then come back it will be collapsed again.  It's making it a bit of a pain to use as you must keep expanding it over and over.

**Comment by sboulema** [comment]
Is the class expand/collapse state in the editor consistent with the expand/collapse state in CodeNav? 
Try collapsing/expanding the class in the editor that might re-subscribe the correct event listeners...

Will look if I can find anything in the code...

**Comment by sboulema** [comment]
You can try this build, see if it makes a difference:
https://github.com/sboulema/CodeNav/releases/tag/v5.0.292

**Comment by sboulema** [comment]
Thanks! The info about difference in behavior depending on side we really helpful!

Found the bug, will resolve tomorrow!

**Comment by sboulema** [comment]
Grab the new release!

https://github.com/sboulema/CodeNav/releases/tag/v5.0.293

**Comment by codinglifestyle** [comment]
Great.  That's done it.  Thank you.
