### ISSUE TITLE
Not load automatically map in large files

### ISSUE THREAD

**Issue by Ifn00b** [sboulema/CodeNav#78]
I have files with +5k lines
When I open some my interface stay freezing for a long time.
If the document contains more than X lines, it would be good to have   press  the Refresh button for load it

Thanks and sorry for my English.

**Comment by sboulema** [comment]
Grab the new release!

https://github.com/sboulema/CodeNav/releases/tag/v5.1.295

**Comment by Ifn00b** [comment]
I love you

VERY VERY THANKS!
