### ISSUE TITLE
Indexer methods ('this[...]') are not recognized, classes with no recognized members are never shown

### ISSUE THREAD

**Issue by Bergam64** [sboulema/CodeNav#79]
Happy New year, Samir!

I hope you are going well.

I've recently noticed 2 issues (for C# code) in the latest CodeNav (5.1.295):

1) Indexer methods are not recognized. Example: for the following class, CodeNav shows only the property SomeProperty:
        private class Test
        {
            internal string this[int index]
            {
                get { return "some value"; }
                set { /* Do something. */ }
            }

            internal string SomeProperty { get; set; }
        }

2) If CodeNav recognizes no member at all in a class, then the class itself doesn't appear in CodeNav. Example: if the above Test class is part of another class (say Parent) and the property SomeProperty is not there (or commented out), then class Test doesn't appear at all in CodeNav for class Parent.

Best regards from Luxembourg,
Didier Prgomet

**Comment by sboulema** [comment]
Grab the new release!
