### ISSUE TITLE
Option to show CodeNav on the right is reset after Visual Studio restarted.

### ISSUE THREAD

**Issue by HTD** [sboulema/CodeNav#8]
To reproduce:
1. Open Visual Studio and any C# file.
2. Use options to show CodeNav on the right side.
3. Close the file and reopen it, CodeNav is displayed correctly.
4. Close Visual Studio and reopen it.
5. See the setting is reset, CodeNav appears on the left side again.

**Comment by sboulema** [comment]
Wow... Stupid mistake, should be fixed in 1.5
