### ISSUE TITLE
The package "CodeNavToolWindowPackage" is not charged correctly

### ISSUE THREAD

**Issue by oblicuo76** [sboulema/CodeNav#87]
When a VS 2015 Project starts, shows a message similar to "An exception is detected that may be caused by a extesion". If CodeNav is disabled, the message is not showed. 
In adition to this, when I clic View-Others Windows-CodeNav shows the message "The package "CodeNavToolWindowPackage" is not charged correctly".

Microsoft Visual Studio Enterprise 2015
Versión 14.0.25431.01 Update 3

Can you help me???

Thank you.

**Comment by oblicuo76** [comment]
Any progress with this bug ?

**Comment by sboulema** [comment]
Any better luck with [v6.0.350](https://github.com/sboulema/CodeNav/releases/tag/v6.0.350) ?

If the error still occurs, can you send me the ActivityLog?
https://devblogs.microsoft.com/visualstudio/troubleshooting-extensions-with-the-activity-log/

**Comment by sboulema** [comment]
Please try the new release [v6.0.352](https://github.com/sboulema/CodeNav/releases/tag/v6.0.352) 🚀

**Comment by sboulema** [comment]
Please try the new release [v6.0.356](https://github.com/sboulema/CodeNav/releases/tag/v6.0.356)

**Comment by oblicuo76** [comment]
Hello,
 
I try reléase 6.0.356 and the toolbar is showed!.  The error message does not appear. CodeNav works fine!

**Comment by sboulema** [comment]
Great to hear it is finally solved!

**Comment by oblicuo76** [comment]
I can finally use this great extesion!! Thank you very much
