### ISSUE TITLE
Issues with collapsible entries

### ISSUE THREAD

**Issue by K-shicsa** [sboulema/CodeNav#89]
Hi,

I use the option "Clicking on an item in the list will take you to that location in the document." very frequently, but it doesn't seem to work well with collapsible entries (switch/enum).
It only works on the lowest level entries (i.e. the switched cases themselves), not the higher levels including function names. Instead, clicking higher levels will just collapse/expand them.
Additionally, the context menu won't work either, so you can't select "Go to Definition" either.
BTW, the Expand/Collapse All Regions options don't work for me either.

Thanks for one of those should-be-programmed-into-VS extensions,
K.

Win10 - VS2019 RC3 (dark) - codenav 6.0.356

**Comment by sboulema** [comment]
**Tasks:**
- Change click behaviour for expendable items
- Enable context menu for expendable items
- Check Expand/Collapse all Regions
  _Currently designed to only do regions, no other collapsibles, maybe that is confusing_

**Comment by K-shicsa** [comment]
> * Change click behaviour for expendable items

IMHO, ideally clicking anywhere but the expand/collapse icon would trigger navigation to the location in the document
> * Enable context menu for expendable items

cool
> * Check Expand/Collapse all Regions
>   _Currently designed to only do regions, no other collapsibles, maybe that is confusing_

Ah, OK. Sorry for my ignorance, but what's a region then? I never saw anything expanding/collapsing with this functionality.

Bedankt!
K.

**Comment by sboulema** [comment]
Grab the new release [v6.1.358](https://github.com/sboulema/CodeNav/releases/tag/v6.1.358)! 🚀

**Comment by K-shicsa** [comment]
Awesome, totally fixed and functional for me :clap::clap::clap:
