### ISSUE TITLE
NullReferenceException when closing file tabs.

### ISSUE THREAD

**Issue by HTD** [sboulema/CodeNav#9]
Following error occurs randomly on closing tabs. I also experienced full Visual Studio crash after closing last tab.

> System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at CodeNav.CodeNav..ctor(IWpfTextViewHost textViewHost, DTE dte) in C:\projects\codenav\CodeNav\CodeNav.cs:line 64&#x000D;&#x000A;   at CodeNav.CodeNavRightFactory.CreateMargin(IWpfTextViewHost wpfTextViewHost, IWpfTextViewMargin marginContainer) in C:\projects\codenav\CodeNav\CodeNavFactory.cs:line 78&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.&lt;AddMargins&gt;b__25_1(IWpfTextViewMarginProvider mp)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)

**Comment by sboulema** [comment]
Added more null checking in the next 1.5 release

**Comment by xperiandri** [comment]
Yep, now works well
