### ISSUE TITLE
CodeNav shows interfaces methods that are implemented in parent

### ISSUE THREAD

**Issue by Cerbere64** [sboulema/CodeNav#91]
Hi,

There is a strange issue on VS2017: CodeNav shows methods from parent interface, even if they are not implemented in the class. So, it shows methods that not exists :

Here, the region "IViewModel", this methods are implemented in parent and not in the current class:
![image](https://user-images.githubusercontent.com/49989377/56745202-371f9b00-677a-11e9-9c16-0f03dfbad8e3.png)

Exemple:
Interface1 : Interface2
class A : B, Interface1 {}

CodeNav shows methods from Interface2 in class A.
And it shows methods from Interface1 even if they are implemented in B.

Result: the navigation don't work well in this case, and sometimes causes a VS crash.

NB: I'm new to github, I don't know how to make this issue a "bug".

Thanks

**Comment by sboulema** [comment]
Thanks for reporting!

Will look into this :)

**Comment by sboulema** [comment]
Thanks for including the small example, that was really helpful in reproducing the bug.

Grab the new release! 🚀

**Comment by Cerbere64** [comment]
So quickly !
Thanks !

There's still maybe a small behavior, this time concerning WPF XAML controls, and methods that are defined in *.g.i.cs files, like InitializeComponent().

![image](https://user-images.githubusercontent.com/49989377/56800366-22dfaa80-681b-11e9-95fd-51d70d7a6b6b.png)

I know this is difficult to determine if it's a "bug" or not, because it's a partial class, and the methods are in the class, but not in the file. I think that CodeNav should only show methods that are in files, not in class. Or if it shows this methods, it maybe should coloring them differently ?
Like this : 

![image](https://user-images.githubusercontent.com/49989377/56800622-c630bf80-681b-11e9-8e3e-8c600d317ff6.png)

I let you choose :)

Thanks again

**Comment by sboulema** [comment]
Again thanks for reporting!

Will look into it :)

**Comment by sboulema** [comment]
Grab the new release! :rocket:

**Comment by Cerbere64** [comment]
Thanks !
Updated to 6.3.362, closed & reopened VS, but I don't see any change ?

**Comment by sboulema** [comment]
Hmm that is weird. It is working on my side, testing with a custom XAML control.

Please verify the installed version of CodeNav, maybe the update failed?
Could you provide a small example piece of code to reproduce?

**Comment by Cerbere64** [comment]
Just have uninstalled / reinstalled CodeNav, the version is 6.3.362:
![image](https://user-images.githubusercontent.com/49989377/56901440-790d5180-6a98-11e9-8293-c0475bf4c945.png)

There is still the behavior on partial classes (xaml views, InitializeComposent method for example):
![image](https://user-images.githubusercontent.com/49989377/56901535-ae19a400-6a98-11e9-95c0-451ebf3fd22b.png)

Actually, the same issue seems happen on partial classes that implements multiples interfaces in different files:
File 1: partial class A: I1
File 2: partial class A: I2...

Exemple, CodeNav seems to show every methods that are in the class:
![image](https://user-images.githubusercontent.com/49989377/56901688-0781d300-6a99-11e9-8e69-3b03a7e598e6.png)

Maybe the issue concerns partial classes globally, not only with interfaced ones ? (removing the interface still showing methods that are not in the file)

Or maybe some kind of refreshing issue ?

Please let me know if you need something else.

Thanks again

**Comment by sboulema** [comment]
Thanks again!

Able to reproduce the problem, looking into it :)

**Comment by sboulema** [comment]
Let's try it again, Grab the new release ([v6.3.363](https://github.com/sboulema/CodeNav/releases/tag/v6.3.363))! 🚀

**Comment by Cerbere64** [comment]
Fast & efficient ! Problem solved !

Thanks a lot
