### ISSUE TITLE
Dropdown instead of docking to editor window

### ISSUE THREAD

**Issue by StevenBonePgh** [sboulema/CodeNav#92]
Mirroring a comment made by another user from the VS Marketplace, Is it possible for the UI to become a drop-down list?  In other words replace the navigation bar, just like Visual Assist X does.

The extension Codist mucks with that bar if you need some example source to check out, though I much prefer the way yours looks and behaves.

Failing this, could it be auto-collapsed some way?

**Comment by sboulema** [comment]
You can collapse CodeNav by double clicking the splitter bar!

Will look into adding a bar layout.

**Comment by StevenBonePgh** [comment]
I saw that one in the wiki, but its hard to position the mouse perfectly and takes a lot longer than hitting the dropdown - this is the approach I am currently using.  The autohide experience is just as bad for different reasons in that it tends to cover the code if you want to jump around.  After deciding to ditch VisualAssist following their price increase for standard license renewals, was looking for alternatives for their awesome replacement - and yours is tops so far. 

Unrelated - Is there a donate link somewhere?  I plan on splitting up my saved license renewal on author donations for the extensions that replaced the few features in VA that I still used...

**Comment by sboulema** [comment]
Understood! Certainly explains the uptick in horizontal bar request lately...

Donations are of course welcome! 
https://beerpay.io/sboulema/CodeNav

**Comment by sboulema** [comment]
[Codist](https://marketplace.visualstudio.com/items?itemName=wmj.Codist)
[Codist - Github](https://github.com/wmjordan/Codist)

**Comment by sboulema** [comment]
Grab the new release! 🚀
