### ISSUE TITLE
Option to ignore regions

### ISSUE THREAD

**Issue by StevenBonePgh** [sboulema/CodeNav#93]
Some like regions, others not... When I am quickly looking for a specific method, I'd prefer to be able to find it based on file order or alphabetically, but the regions tend to get in the way more than be helpful.  A button to toggle regions off/on would be fantastic!

**Comment by sboulema** [comment]
Grab the new release! :rocket:

**Comment by StevenBonePgh** [comment]
Excellent!  Thank you for your hard work and quick response!

**Comment by StevenBonePgh** [comment]
It looks like the checkbox for ignoring regions is now missing, and after resetting settings because I noticed some methods were missing, regions are back.  I expected the new 'Ignore' column would work with Regions - I added two Region filters one with All and the other with Unknown Access, and checked ignore for both and the regions still show up.  Am I doing something wrong now?  Thanks!

**Comment by sboulema** [comment]
Unable to reproduce that :(

I have a filter for 'All' 'Regions' set to 'Ignore' and it works for me. Do you have an example file/code structure so that I can reproduce it locally?
