### ISSUE TITLE
Nested regions

### ISSUE THREAD

**Issue by Cerbere64** [sboulema/CodeNav#95]
Hi,

It seems that there is a behavior with nested regions:

![image](https://user-images.githubusercontent.com/49989377/58008692-36fe8b00-7aed-11e9-88ad-7cd7f5c2c77a.png)

As you can see, for regions with children, CodeNav add a second empty region (mother & child) at the end.

Thank you.

**Comment by sboulema** [comment]
Thanks for reporting!

Able to reproduce this behaviour, will look into fixing this 👍

**Comment by sboulema** [comment]
Grab the new release! 🚀

**Comment by Cerbere64** [comment]
Perfect !
Thanks a lot !
