### ISSUE TITLE
Search not working. VS2019 16.0.4

### ISSUE THREAD

**Issue by kowgli** [sboulema/CodeNav#96]
Whatever I type in the search field - it doesn't show any results.

Visual Studio 2019, version 16.0.4

https://screencast-o-matic.com/watch/cqhrjVTjtH

I tried reinstalling the extension, didn't help.

BTW - thanks for this wonderful extension. Should be built into VS :)

**Comment by sboulema** [comment]
Thanks for reporting and the kind words!

Will look into fixing this 😄

**Comment by sboulema** [comment]
Grab the new release! :rocket:

**Comment by kowgli** [comment]
> Grab the new release! 🚀

Works! Great job, thanks a lot.
