### ISSUE TITLE
Background color 

### ISSUE THREAD

**Issue by sotektom** [sboulema/CodeNav#98]
Hi, it's not issue, but question. Are you expecting, the background color of window could be changed?.

**Comment by sboulema** [comment]
The CodeNav background color responds to all the visual studio themes (Light, Dark, Blue).

Manually changing the background color is not (yet) possible at the moment. Would you like to see that feature added?

**Comment by sotektom** [comment]
HI, it could be fine to include such feature. I would like to be able to change Color settings of codenav independently on main VS theme. I discussed it with my collegues using your extension and all of us would like see this feature. This VSIX is very usefull for us, so thanks a lot for it.

Have a nice day

Tom

**Comment by sboulema** [comment]
Grab the new release! 🚀 

https://github.com/sboulema/CodeNav/releases/tag/v7.0.382

**Comment by sotektom** [comment]
Hi Samir,
Thanks a lot, thats it, what I need. One bug is there, there is no way to change highlite color, but it doesn’t matter.

Tom
